sudo: required
services:
  - docker

before_install:
  - docker build -t danaya/urlshortener .

script:
  - docker run danaya/urlshortener npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "urlshortener"
  env: "Urlshortener-env"
  bucket_name: "elasticbeanstalk-eu-west-1-898544430015"
  bucket_path: "urlshortener"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
