version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports:
      - "3000:3000"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - HOST=http://localhost
      - PORT=3000
